# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Build with Python 3.9 on the latest version of Ubuntu.
build:
  os: ubuntu-22.04
  tools:
    python: '3.9'

# Build documentation in the docs/ directory with Sphinx.
sphinx:
  configuration: docs/conf.py

# Install extra requirements for the documentation.
python:
  install:
    - method: pip
      path: '.'
      extra_requirements:
        - doc
