coverage:
  range: "50...100"
  ignore:          # files and folders that will be removed during processing
    - "**/tests"
    - "pydra/_version.py"
  status:
    project:
      default:
        threshold: 1
    patch:
      default:
        target: 80
