docs_deploy: &docs
  docker:
    - image: node:8.10.0
  working_directory: /tmp/gh-pages
  steps:
    - run:
        name: Check whether this is the original repo
        command: |
          if [[ "$CIRCLE_PROJECT_USERNAME" != "nipype" ]]; then
              echo "Not in nipype/pydra - skipping docs deploy."
              circleci step halt
          fi
    - add_ssh_keys:
        fingerprints:
          - "21:5b:2f:41:9e:e6:7a:47:e7:90:37:62:b2:ac:e8:a0"
    - run:
        name: Install gh-pages tool
        command: |
          npm install -g --silent gh-pages@3.0.0
    - checkout
    - run:
        name: Set git settings
        command: |
          git config user.email "nipype@mit.edu"
          git config user.name "Nipype Bot"
    - attach_workspace:
        at: docs/_build
    - run:
        name: Disable jekyll builds
        command: touch docs/_build/html/.nojekyll
    - run:
        name: Deploy docs to gh-pages branch
        command: gh-pages --no-history --dotfiles --message "doc(update) [skip ci]" --dist docs/_build/html

version: 2
jobs:

  build_docs:
    docker:
      - image: python:3.7.4
    working_directory: /tmp/gh-pages
    environment:
      - FSLOUTPUTTYPE: NIFTI
      - SUBJECTS_DIR: /tmp/subjects
    steps:
      - checkout
      - run:
          name: Install deps
          command: |
            pip install --upgrade pip
            pip install --no-cache-dir -r docs/requirements.txt
            pip install --no-cache-dir .[doc]
      - run:
          name: Build only this commit
          command: make -C docs SPHINXOPTS="-W" BUILDDIR="_build/no_version_html" SPHINX_APIDOC_OPTIONS="members,undoc-members,show-inheritance,noindex" html
      - store_artifacts:
          path: ./docs/_build/no_version_html
      - run:
          name: Stop or generate versioned docs?
          command: |
            set +e
            force_versioned="$( git log --format=oneline -n 1 $CIRCLE_SHA1 | grep -i -E '\[docs?[ _]?versions?\]' )"
            set -e
            if [[ "x${CIRCLE_TAG}" = "x" && "${CIRCLE_BRANCH}" != "master" && "x${force_versioned}" = "x" ]]; then
              echo "Not a tag or master branch - skipping versioned docs."
              circleci step halt
            fi
      - restore_cache:
          keys:
            - docs-v1-{{ .Branch }}-{{ .Revision }}
            - docs-v1-{{ .Branch }}-
            - docs-v1-master
            - docs-v1-
          paths:
            - ./docs/_build/_html
      - run:
          name: Generate Versioned Docs
          command: make -f ./docs/Makefile versioned CURBRANCH=${CIRCLE_TAG:-$CIRCLE_BRANCH}
      - save_cache:
          key: docs-v1-{{ .Branch }}-{{ .Revision }}
          paths:
            - ./docs/_build/_html
      - persist_to_workspace:
          root: docs/_build
          paths: html
      - store_artifacts:
          path: ./docs/_build/html

  deploy_docs_tag:
    <<: *docs

  deploy_docs_master:
    <<: *docs


workflows:
  version: 2
  build_deploy:
    jobs:
      - build_docs:
          filters:
            branches:
              ignore:
                - /tests?\/.*/
            tags:
              only: /.*/
      - deploy_docs_master:
          requires:
            - build_docs
          filters:
            branches:
              only: /master/
            tags:
              ignore: /.*/
      - deploy_docs_tag:
          requires:
            - build_docs
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
