#!/usr/bin/env python3
from configparser import ConfigParser
from pathlib import Path

repo_root = Path(__file__).parent.parent
setup_cfg = repo_root / "setup.cfg"
min_reqs = repo_root / "min-requirements.txt"

config = ConfigParser()
config.read(setup_cfg)
requirements = config.get("options", "install_requires").strip().splitlines()

lines = ["# Auto-generated by tools/update_min_requirements.py", ""]

lines[1:-1] = [req.replace(">=", "==").replace("~=", "==") for req in requirements]

min_reqs.write_text("\n".join(lines))
