parameters:
  name: ''
  vmImage: ''
  matrix: []

jobs:
- job: ${{ parameters.name }}
  pool:
    vmImage: ${{ parameters.vmImage }}
  variables:
    DEPENDS: "-r min-requirements.txt"
    CHECK_TYPE: test
  strategy:
    matrix:
      ${{ insert }}: ${{ parameters.matrix }}

  steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(PYTHON_VERSION)'
        addToPath: true
        architecture: '$(PYTHON_ARCH)'
    - script: |
        echo %PYTHONHASHSEED%
      displayName: 'Display hash seed'
    - script: |
        python -m pip install --upgrade pip==18.1 setuptools==30.2.1 wheel
      displayName: 'Update build tools'
    - script: |
        python -m pip install %DEPENDS%
      displayName: 'Install dependencies'
    - script: |
        python -m pip install .[$(CHECK_TYPE)]
      displayName: 'Install pydra'
    - script: |
        pytest -vs -n auto --cov pydra --cov-config .coveragerc --cov-report xml:cov.xml --doctest-modules pydra
      displayName: 'Pytest tests'
    - script: |
        python -m pip install codecov
        codecov --file cov.xml
      displayName: 'Upload To Codecov'
      env:
        CODECOV_TOKEN: $(CODECOV_TOKEN)
